name: build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Format
      run: |
        rustup component add rustfmt
        cargo fmt --all -- --check

    - name: Lint
      run: |
        rustup component add clippy
        cargo clippy -- -D warnings

    - name: Build
      run: cargo build --verbose --release

    - name: Run tests
      run: cargo test --verbose --lib

    - name: Code audit
      run: |
        cargo install cargo-audit
        cargo audit
